"""add_user_stats_table

Revision ID: 06a93be29550
Revises: 68f44b4a2b18
Create Date: 2026-04-30 14:37:12.500964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a93be29550'
down_revision: Union[str, None] = '68f44b4a2b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_level_xp', sa.Integer(), nullable=False),
    sa.Column('xp_to_next_level', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_progress_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Enum('D', 'C', 'B', 'A', 'S', 'SS', name='rankcategory'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_id'), 'user_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_id'), table_name='user_stats')
    op.drop_table('user_stats')
    # ### end Alembic commands ###
