"""add timezone to users

Revision ID: 675f65a5d7a4
Revises: 06a93be29550
Create Date: 2026-06-24 15:54:21.764407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675f65a5d7a4'
down_revision: Union[str, None] = '06a93be29550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True, server_default="UTC"))
    op.alter_column('users', 'timezone', nullable=False, server_default=None, existing_type=sa.String(length=50))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
