"""add timer sessions

Revision ID: 68f44b4a2b18
Revises: c1fcdbda9ab7
Create Date: 2026-03-19 16:28:53.786855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68f44b4a2b18'
down_revision: Union[str, None] = 'c1fcdbda9ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'canceled', 'expired', name='timerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_one_running_timer_per_habit', 'timer_sessions', ['habit_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_index(op.f('ix_timer_sessions_id'), 'timer_sessions', ['id'], unique=False)
    op.add_column('habit_completions', sa.Column('timer_session_id', sa.Integer(), nullable=True))
    op.alter_column('habit_completions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'habit_completions', ['timer_session_id'])
    op.create_foreign_key(None, 'habit_completions', 'timer_sessions', ['timer_session_id'], ['id'])
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('habits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('habits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'habit_completions', type_='foreignkey')
    op.drop_constraint(None, 'habit_completions', type_='unique')
    op.alter_column('habit_completions', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('habit_completions', 'timer_session_id')
    op.drop_index(op.f('ix_timer_sessions_id'), table_name='timer_sessions')
    op.drop_index('ix_one_running_timer_per_habit', table_name='timer_sessions', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('timer_sessions')
    # ### end Alembic commands ###
